<%# Handle old behaviour of official mysql image %>
<% user = ENV.key?("MYSQL_ROOT_PASSWORD") ? "root" : ENV["MYSQL_USER"] %>
<% password = ENV.key?("MYSQL_ROOT_PASSWORD") ? ENV["MYSQL_ROOT_PASSWORD"] : ENV["MYSQL_PASSWORD"] %>
development:
  adapter: mysql2
  database: sampledb
  username: nvali
  password: Sunny
  host: mysql
  port: 3306

test:
  adapter: mysql2
  database: sampledb
  username: nvali
  password: Sunny
  host: mysql
  port: 3306

production:
  adapter: mysql2
  database: sampledb
  username: nvali
  password: Sunny
  host: mysql
  port: 3306
